Script started on Sun 03 Apr 2016 07:24:06 PM MDT
]0;matt@matt-XPS-15-9530: ~/Dropbox/122Coding/ComplexityProjectmatt@matt-XPS-15-9530:~/Dropbox/122Coding/ComplexityProject$ make
gcc -g -Wall -o main main.o blackbox.o
]0;matt@matt-XPS-15-9530: ~/Dropbox/122Coding/ComplexityProjectmatt@matt-XPS-15-9530:~/Dropbox/122Coding/ComplexityProject$ valgrind --leak-check=yes ./main -f 2 -n 100[1P[1@3
==14972== Memcheck, a memory error detector
==14972== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==14972== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==14972== Command: ./main -f 3 -n 100
==14972== 
Sorted Ascending List:
100 0.002
100 0.000
100 0.000
100 0.000
100 0.000
Sorted Descending List:
100 0.000
100 0.000
100 0.000
100 0.000
100 0.000
Randomized List:
100 0.000
100 0.000
100 0.000
100 0.000
100 0.000
==14972== 
==14972== HEAP SUMMARY:
==14972==     in use at exit: 0 bytes in 0 blocks
==14972==   total heap usage: 15 allocs, 15 frees, 12,000 bytes allocated
==14972== 
==14972== All heap blocks were freed -- no leaks are possible
==14972== 
==14972== For counts of detected and suppressed errors, rerun with: -v
==14972== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;matt@matt-XPS-15-9530: ~/Dropbox/122Coding/ComplexityProjectmatt@matt-XPS-15-9530:~/Dropbox/122Coding/ComplexityProject$ valgrind --leak-check=yes ./main -f 3 -n 100[1P[1@6[C[C[C[C[C[C[C
==14975== Memcheck, a memory error detector
==14975== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==14975== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==14975== Command: ./main -f 6 -n 100
==14975== 
Sorted Ascending List:
100 0.001
100 0.000
100 0.000
100 0.000
100 0.000
Sorted Descending List:
100 0.000
100 0.000
100 0.000
100 0.000
100 0.000
Randomized List:
100 0.000
100 0.000
100 0.000
100 0.000
100 0.000
==14975== 
==14975== HEAP SUMMARY:
==14975==     in use at exit: 0 bytes in 0 blocks
==14975==   total heap usage: 15 allocs, 15 frees, 12,000 bytes allocated
==14975== 
==14975== All heap blocks were freed -- no leaks are possible
==14975== 
==14975== For counts of detected and suppressed errors, rerun with: -v
==14975== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;matt@matt-XPS-15-9530: ~/Dropbox/122Coding/ComplexityProjectmatt@matt-XPS-15-9530:~/Dropbox/122Coding/ComplexityProject$ exit
exit

Script done on Sun 03 Apr 2016 07:25:05 PM MDT
