Matthew Olsen
02-11-2015
Lab 8

PROGRAM WAS RUN USING VALGRIND TO SHOW ALLOCATED MEMORY WAS FREED PROPERLY

Script started on Mon 02 Nov 2015 03:07:03 PM MST
]0;matt@matt-XPS-15-9530: ~/Dropbox/113Coding/lab8matt@matt-XPS-15-9530:~/Dropbox/113Coding/lab8$ valgrind --leak-chc[Keck=yes ./lab8 
[A
==4171== Memcheck, a memory error detector
==4171== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==4171== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==4171== Command: ./lab8
==4171== 
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 3
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 1
1. Enter a number at the head.
2. Enter a number in the middle.
3. Enter a number at the tail.
Select number: 
I do not understand 0.
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 1
1. Enter a number at the head.
2. Enter a number in the middle.
3. Enter a number at the tail.
Select number: 1
Input x:13.2
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 1
1. Enter a number at the head.
2. Enter a number in the middle.
3. Enter a number at the tail.
Select number: 2
Input x:14.5
Input pos:5
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 3
Address of node: 0x51fc040	x: 13.200000	*next: 0x51fc090

Address of node: 0x51fc090	x: 14.500000	*next: NULL

What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 1
1. Enter a number at the head.
2. Enter a number in the middle.
3. Enter a number at the tail.
Select number: 3
Input x:14.5
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 3
Address of node: 0x51fc040	x: 13.200000	*next: 0x51fc090

Address of node: 0x51fc090	x: 14.500000	*next: 0x51fc0e0

Address of node: 0x51fc0e0	x: 14.500000	*next: NULL

What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 1
1. Enter a number at the head.
2. Enter a number in the middle.
3. Enter a number at the tail.
Select number: 1
Input x:1
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 3
Address of node: 0x51fc130	x: 1.000000	*next: 0x51fc040

Address of node: 0x51fc040	x: 13.200000	*next: 0x51fc090

Address of node: 0x51fc090	x: 14.500000	*next: 0x51fc0e0

Address of node: 0x51fc0e0	x: 14.500000	*next: NULL

What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 4
There are 4 nodes.
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 5
Find x:9
Did not find 9.000000 in the list.
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 5
Find x:14.5
Found 14.500000 at node 0x51fc090.
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 3
Address of node: 0x51fc130	x: 1.000000	*next: 0x51fc040

Address of node: 0x51fc040	x: 13.200000	*next: 0x51fc090

Address of node: 0x51fc090	x: 14.500000	*next: 0x51fc0e0

Address of node: 0x51fc0e0	x: 14.500000	*next: NULL

What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 2
Input number to delete: 14.5
What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 3
Address of node: 0x51fc130	x: 1.000000	*next: 0x51fc040

Address of node: 0x51fc040	x: 13.200000	*next: 0x51fc0e0

Address of node: 0x51fc0e0	x: 14.500000	*next: NULL

What would you like to do?
1. Enter a number.
2. Delete a number.
3. Print all numbers.
4. Print number of items in a list.
5. Find if a number is in the list.
6. Quit program.
Select number: 6
Goodbye!
==4171== 
==4171== HEAP SUMMARY:
==4171==     in use at exit: 0 bytes in 0 blocks
==4171==   total heap usage: 4 allocs, 4 frees, 64 bytes allocated
==4171== 
==4171== All heap blocks were freed -- no leaks are possible
==4171== 
==4171== For counts of detected and suppressed errors, rerun with: -v
==4171== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;matt@matt-XPS-15-9530: ~/Dropbox/113Coding/lab8matt@matt-XPS-15-9530:~/Dropbox/113Coding/lab8$ exit
exit

Script done on Mon 02 Nov 2015 03:11:03 PM MST
