Matthew Olsen
2015-10-28
Lab 7

Script started on Mon 26 Oct 2015 07:15:27 PM MDT
]0;matt@matt-XPS-15-9530: ~/Dropbox/113Coding/lab7matt@matt-XPS-15-9530:~/Dropbox/113Coding/lab7$ valgrind --leak-check=yes ./a.ou 
t
==3195== Memcheck, a memory error detector
==3195== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==3195== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==3195== Command: ./a.out
==3195== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==3195== 
==3195== HEAP SUMMARY:
==3195==     in use at exit: 43 bytes in 1 blocks
==3195==   total heap usage: 1 allocs, 0 frees, 43 bytes allocated
==3195== 
==3195== 43 bytes in 1 blocks are definitely lost in loss record 1 of 1
==3195==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3195==    by 0x400737: main (dynamic_string.c:19)
==3195== 
==3195== LEAK SUMMARY:
==3195==    definitely lost: 43 bytes in 1 blocks
==3195==    indirectly lost: 0 bytes in 0 blocks
==3195==      possibly lost: 0 bytes in 0 blocks
==3195==    still reachable: 0 bytes in 0 blocks
==3195==         suppressed: 0 bytes in 0 blocks
==3195== 
==3195== For counts of detected and suppressed errors, rerun with: -v
==3195== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
]0;matt@matt-XPS-15-9530: ~/Dropbox/113Coding/lab7matt@matt-XPS-15-9530:~/Dropbox/113Coding/lab7$ exit
exit

Script done on Mon 26 Oct 2015 07:16:05 PM MDT
